/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.perbankanextendmaven.View;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import com.mycompany.perbankanextendmaven.Entity.*;
import com.mycompany.perbankanextendmaven.View.*;
import com.mycompany.perbankanextendmaven.App.*;

/**
 *
 * @author Dukhaan
 */
public class TambahUangView extends javax.swing.JPanel {

    private javax.swing.JTable tableNasabah;
    private MainFrame mainFrame;
    private Nasabah nasabah;

    /**
     * Creates new form TambahUangView
     */
    public TambahUangView(MainFrame mainFrame, Nasabah nasabah) {
        initComponents();
        this.mainFrame = mainFrame;
        this.nasabah = nasabah;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        inputSimpanUang = new javax.swing.JTextField();
        buttonSimpanSimpan = new javax.swing.JButton();
        buttonKembaliSimpan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(36, 34, 49));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel3.setText("Masukkan uang :");

        inputSimpanUang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSimpanUangActionPerformed(evt);
            }
        });

        buttonSimpanSimpan.setBackground(new java.awt.Color(51, 153, 255));
        buttonSimpanSimpan.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        buttonSimpanSimpan.setText("Simpan");
        buttonSimpanSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanSimpanActionPerformed(evt);
            }
        });

        buttonKembaliSimpan.setBackground(new java.awt.Color(237, 99, 99));
        buttonKembaliSimpan.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        buttonKembaliSimpan.setText("Kembali");
        buttonKembaliSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliSimpanActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(31, 29, 43));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(241, 240, 242));
        jLabel4.setText("Simpan Uang");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(230, 230, 230))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonSimpanSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(buttonKembaliSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inputSimpanUang, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputSimpanUang, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSimpanSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonKembaliSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputSimpanUangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSimpanUangActionPerformed

        Bank bank = new Bank();

        String newSaldo = inputSimpanUang.getText();

        try {
            // Mengonversi newSaldo menjadi tipe data integer
            int jumlahSaldo = Integer.parseInt(newSaldo);
            int selectedRow = tableNasabah.getSelectedRow();

            if (selectedRow >= 0) {
                int rowIndex = tableNasabah.convertRowIndexToModel(selectedRow);

                if (nasabah != null) {
                    Tabungan tabungan = nasabah.getTabungan();

                    if (jumlahSaldo <= 0) {
                        JOptionPane.showMessageDialog(this, "Jumlah saldo yang akan disimpan harus lebih dari 0.", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        tabungan.simpanUang(jumlahSaldo);

                        DefaultTableModel model = (DefaultTableModel) tableNasabah.getModel();
                        model.setValueAt(tabungan.getSaldo(), selectedRow, 3);

                        inputSimpanUang.setText("");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Pilih baris Nasabah yang akan menambahkan saldo.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan jumlah saldo yang valid.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_inputSimpanUangActionPerformed

    private void buttonSimpanSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanSimpanActionPerformed

        if (nasabah != null) {
            // Memeriksa apakah inputSaldo kosong atau tidak
            if (inputSimpanUang.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Isi jumlah saldo yang akan disimpan.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    // Mendapatkan jumlah saldo yang akan disimpan dari inputSaldo
                    String jumlahSimpan = inputSimpanUang.getText(); // Mengubah ke String
                    JOptionPane.showMessageDialog(this, "Saldo berhasil disimpan.", "Success", JOptionPane.INFORMATION_MESSAGE);


                    // Memastikan jumlahSimpan positif
                    int saldoTambahan = Integer.parseInt(jumlahSimpan);
                    if (saldoTambahan <= 0) {
                        JOptionPane.showMessageDialog(this, "Jumlah saldo yang akan disimpan harus lebih dari 0.", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        // Mendapatkan objek Tabungan dari Nasabah
                        Tabungan tabungan = nasabah.getTabungan();

                        // Menyimpan saldo sesuai dengan jumlahSimpan
                        tabungan.simpanUang(saldoTambahan);

                        // Mengosongkan inputSaldo
                        inputSimpanUang.setText("");
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Masukkan jumlah saldo yang valid.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        mainFrame.showView(new BankView(mainFrame));
    }//GEN-LAST:event_buttonSimpanSimpanActionPerformed

    private void buttonKembaliSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliSimpanActionPerformed
        mainFrame.showView(new BankView(mainFrame));
    }//GEN-LAST:event_buttonKembaliSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonKembaliSimpan;
    private javax.swing.JButton buttonSimpanSimpan;
    private javax.swing.JTextField inputSimpanUang;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
