/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.perbankanextendmaven.View;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import com.mycompany.perbankanextendmaven.Entity.*;
import com.mycompany.perbankanextendmaven.View.*;
import com.mycompany.perbankanextendmaven.App.*;

/**
 *
 * @author Dukhaan
 */
public class TarikUangView extends javax.swing.JPanel {

    private javax.swing.JTable tableNasabah;
    private MainFrame mainFrame;
    private Nasabah nasabah;

    /**
     * Creates new form TarikUangView
     */
    public TarikUangView(MainFrame mainFrame, Nasabah nasabah) {
        initComponents();
        this.mainFrame = mainFrame;
        this.nasabah = nasabah;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        inputAmbilUang = new javax.swing.JTextField();
        buttonSimpanAmbil = new javax.swing.JButton();
        buttonKembaliAmbil = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(36, 34, 49));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel3.setText("Masukkan uang :");

        inputAmbilUang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAmbilUangActionPerformed(evt);
            }
        });

        buttonSimpanAmbil.setBackground(new java.awt.Color(51, 153, 255));
        buttonSimpanAmbil.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        buttonSimpanAmbil.setText("Simpan");
        buttonSimpanAmbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanAmbilActionPerformed(evt);
            }
        });

        buttonKembaliAmbil.setBackground(new java.awt.Color(237, 99, 99));
        buttonKembaliAmbil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonKembaliAmbil.setText("Kembali");
        buttonKembaliAmbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliAmbilActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(31, 29, 43));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(241, 240, 242));
        jLabel4.setText("Tarik Uang");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonSimpanAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(buttonKembaliAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inputAmbilUang, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputAmbilUang, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonKembaliAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSimpanAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputAmbilUangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAmbilUangActionPerformed
        Bank bank = new Bank();

        String tarikanSaldo = inputAmbilUang.getText();

        try {
            // Mengonversi tarikanSaldo menjadi tipe data integer
            int jumlahTarikan = Integer.parseInt(tarikanSaldo);
            int selectedRow = tableNasabah.getSelectedRow();

            if (selectedRow >= 0) {
                int rowIndex = tableNasabah.convertRowIndexToModel(selectedRow);
                Nasabah nasabah = bank.getNasabah(rowIndex);

                if (nasabah != null) {
                    Tabungan tabungan = nasabah.getTabungan();

                    if (jumlahTarikan <= 0) {
                        JOptionPane.showMessageDialog(this, "Jumlah saldo yang akan ditarik harus lebih dari 0.", "Error", JOptionPane.ERROR_MESSAGE);
                    } else if (jumlahTarikan > tabungan.getSaldo()) {
                        JOptionPane.showMessageDialog(this, "Saldo tidak mencukupi untuk penarikan ini.", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        tabungan.ambilUang(jumlahTarikan);

                        DefaultTableModel model = (DefaultTableModel) tableNasabah.getModel();
                        model.setValueAt(tabungan.getSaldo(), selectedRow, 3);

                        inputAmbilUang.setText("");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Pilih baris Nasabah yang akan menarik saldo.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan jumlah saldo yang valid.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_inputAmbilUangActionPerformed

    private void buttonSimpanAmbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanAmbilActionPerformed
        if (nasabah != null) {
            // Memeriksa apakah inputSaldo kosong atau tidak
            if (inputAmbilUang.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Isi jumlah saldo yang akan diambil.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    // Mendapatkan jumlah saldo yang akan diambil dari inputSaldo
                    String jumlahAmbil = inputAmbilUang.getText(); // Mengubah ke String
                    JOptionPane.showMessageDialog(this, "Saldo berhasil diambil.", "Success", JOptionPane.INFORMATION_MESSAGE);

                    // Memastikan jumlahAmbil positif
                    int saldoPengurangan = Integer.parseInt(jumlahAmbil);
                    if (saldoPengurangan <= 0) {
                        JOptionPane.showMessageDialog(this, "Jumlah saldo yang akan diambil harus lebih dari 0.", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        // Mendapatkan objek Tabungan dari Nasabah
                        Tabungan tabungan = nasabah.getTabungan();

                        // Memeriksa apakah saldo mencukupi untuk pengurangan
                        if (saldoPengurangan > tabungan.getSaldo()) {
                            JOptionPane.showMessageDialog(this, "Saldo tidak mencukupi untuk pengurangan ini.", "Error", JOptionPane.ERROR_MESSAGE);
                        } else {
                            // Mengurangkan saldo sesuai dengan jumlahAmbil
                            tabungan.ambilUang(saldoPengurangan);

                            // Mengosongkan inputSaldo
                            inputAmbilUang.setText("");
                        }
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Masukkan jumlah saldo yang valid.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        mainFrame.showView(new BankView(mainFrame));
    }//GEN-LAST:event_buttonSimpanAmbilActionPerformed

    private void buttonKembaliAmbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliAmbilActionPerformed
        mainFrame.showView(new BankView(mainFrame));
    }//GEN-LAST:event_buttonKembaliAmbilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonKembaliAmbil;
    private javax.swing.JButton buttonSimpanAmbil;
    private javax.swing.JTextField inputAmbilUang;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
